### ISSUE TITLE
When will code released?

### ISSUE THREAD

**Issue by WhuRan** [clovaai/units#1]
Thanks for your great job! When will code released?

**Comment by lilong-wen** [comment]
This is weird, last time I checked I think I saw they open-sourced code, I don't know why they deleted the whole thing, or maybe I see it wrong.

**Comment by lerndeep** [comment]
@ClovaAIAdmin  following

**Comment by taeho-kil** [comment]
I apologize for the delay in the release. We have now made our open-source materials available, including training and testing code, as well as the trained model. Thank you.
